Models/ErrorViewModel.cs
namespace EntityApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EntityApp.Models;

namespace EntityApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/KursController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace efcoreApp.Controllers
{

    public class KursController : Controller
    {

        private readonly DataContext _context;

        public KursController(DataContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index()
        {
            return View(await _context.Kurslar.ToListAsync());
        }


        public async Task<IActionResult> Create()
        {

            ViewBag.Ogretmenler = new SelectList(await _context.Ogretmenler.ToListAsync(), "OgretmenId", "Ad");
            return View();


        }

        [HttpPost]
        public async Task<IActionResult> Create(Kurs model)
        {

            _context.Kurslar.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }




        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }



            var kurs = await _context
                                    .Kurslar
                                    .AsNoTracking()
                                    .Where(o => o.KursId == id)
                                    .Include(x => x.Ogretmen)
                                    .Include(o => o.KursKayitlari)
                                    .ThenInclude(o => o.Ogrenci)
                                    .FirstOrDefaultAsync();



            if (kurs == null)
            {
                return NotFound();
            }

            return View(kurs);

        }


        [HttpPost]
        public async Task<IActionResult> Edit(int? KursId, Kurs model)
        {
            if (KursId != model.KursId)
            {

                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();

                }
                catch (System.Exception)
                {

                    throw;
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {

            var kurs = await _context.Kurslar.FindAsync(id);
            if (kurs == null)
            {
                return NotFound();

            }

            _context.Kurslar.Remove(kurs);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }

    }



}

Controllers/KursKayıtController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace efcoreApp.Controllers  
{
    public class KursKayitController : Controller
    {
        private readonly DataContext _context;


        public KursKayitController(DataContext context)
        {
            _context = context;
        }


         

        public IActionResult Index()  
        {
            
            var kayitlar = _context.KursKayıtları
            .Include(x=>x.Ogrenci)
            .Include(x=> x.Kurs).ToList();
            return View(kayitlar);  
        }

   public IActionResult Create()  
        {
            ViewBag.Ogrenciler = new SelectList( _context.Ogrenciler.ToList(), "Id" ,"AdSoyad");
            ViewBag.Kurslar = new SelectList( _context.Kurslar.ToList(), "KursId" ,"Baslik");
            return View();  
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
         public async Task<IActionResult> Create(KursKayıt model)
         {
            model.KayıtTarihi = DateTime.Now;
            _context.KursKayıtları.Add(model);

            await _context.SaveChangesAsync();

            return RedirectToAction("");

               

         }










    }
}

Controllers/OgrenciController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace efcoreApp.Controllers
{

    public class OgrenciController : Controller
    {


        private readonly DataContext _context;

        public OgrenciController(DataContext context){
            _context = context;
        }


        
        public async Task <IActionResult> Index()
        {
          
            return View( await _context.Ogrenciler.ToListAsync());
        }








        public IActionResult Create()
        {
            return View();


        }


        [HttpPost]
        public async Task<IActionResult> Create(Ogrenci model)
        {

            _context.Ogrenciler.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

            }

        


        public async Task<IActionResult> Edit(int? id){

            if(id == null){
                return NotFound();
            }

              var ogr =await _context.Ogrenciler
                                .Where(o => o.Id == id)
                                .Include(o => o.KursKayitları)
                                .ThenInclude(o => o.Kurs)
                                .FirstOrDefaultAsync();
                                // .Include(o => o.KursKayitları)
                                // .ThenInclude(o => o.Kurs)
                                // .FirstOrDefaultAsync(o => o.Id == id);
            
            if(ogr == null){

                return NotFound();

              }

            return View(ogr);

        }    


        [HttpPost]
        [ValidateAntiForgeryToken]
       public async Task<IActionResult> Edit(int id, Ogrenci model)
        {
            if(id != model.Id){

                return NotFound();

            }
            if(ModelState.IsValid){
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException )
                {
                   if(!_context.Ogrenciler.Any(o => o.Id == model.Id)){

                    return NotFound();

                   }
                   else{
                    throw;
                   }
                }
                 return  RedirectToAction("Index");
            }
                return View();

           
        }



        [HttpGet]

        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null){

                return NotFound();
            }    

            var ogr = await _context.Ogrenciler.FindAsync(id);
            if(ogr == null){
                return NotFound();

            }

            return View(ogr);
        }

        
        [HttpPost]
        public async Task<IActionResult> ToDelete(int? id)
        {
            var ogr = await _context.Ogrenciler.FindAsync(id);
            if (ogr == null){
                return NotFound();
            }

            _context.Ogrenciler.Remove(ogr);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        

}







}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Kurs/Create.cshtml
@model Kurs

<h2>Kurs Ekle </h2>
<hr>


<form asp-controller="Kurs" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Baslik" class="form-label">Kurs Adı</label>
        <input asp-for="Baslik" class="form-control">
    </div>

    <div class="mb-3">

        <label asp-for="OgretmenId" class="form-label">Öğretmen</label>

        <select asp-for="OgretmenId" asp-items="ViewBag.Ogretmenler" class="form-select">
            <option value="">Seçiniz</option>
        </select>
    </div>





    <button type="submit" class="btn btn-secondary">Kaydet</button>
    </div>



</form>

Views/Kurs/Edit.cshtml
@model Kurs

<h2>Kurs Güncelle</h2>

<hr>

<div class="row col-12" >
    <div class="col-4"></div>


        <form asp-controller="Kurs" asp-action="Edit" method="post">

            <input type="hidden" asp-for="KursId">
            <div class="mb-3">
                <label asp-for="Baslik" class="form-label">Kurs Adı</label>
                <input asp-for="Baslik" class="form-control">

                <button type="submit" class="btn btn-primary">Kaydet</button>


        </form>

    </div>


    <div class="col-4">

    <h4>Öğrenciler</h4>
        <hr>
              <ul>
            @foreach(var item in @Model.KursKayitlari){
                <li>@item.Ogrenci.AdSoyad</li>
            }
        </ul>




    </div>


        <div class="col-4">

    <h4>Öğretmenler</h4>
        <hr>
              <ul>
           
                <li>@Model.Ogretmen?.Ad</li>
            
        </ul>




    </div>

</div>

Views/Kurs/Index.cshtml
@model IEnumerable<Kurs>

<table class="table">

    <a href="/Kurs/Create" class="btn btn-primary" >  Kurs Ekle  </a>

    <thead>

        <tr>
            <th>Kurs Id</th>
            <th>Kurs Ad</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var kurs in Model)
        {
            <tr>
                <td>@kurs.KursId</td>
                <td>@kurs.Baslik</td>
                <td></td>
                <td>
                    <a asp-controller="Kurs"  asp-action="Edit" asp-route-id = "@kurs.KursId"  class="btn btn-sm btn-primary">Detay and Edit</a>
                   
                   <form asp-controller="Kurs" asp-action="Delete" method="post">
                    <input  type="hidden" value="@kurs.KursId" name="id">
                    <button type="submit" asp-controller="Kurs" asp-action="Delete" asp-route-id = "@kurs.KursId" class="btn btn-sm btn-danger">Delete</button>

                   </form> 
                </td>
            </tr>
        }
    </tbody>
</table>

Views/KursKayit/Create.cshtml
@model KursKayıt

<form asp-controller="KursKayit" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="OgrenciId" class="form-label">Öğrenci</label>
        <select asp-for="OgrenciId" asp-items="ViewBag.Ogrenciler" class="form-control"></select>
    </div>
    <div class="mb-3">
        <label asp-for="KursId" class="form-label">Kurs</label>
        <select asp-for="KursId" asp-items="ViewBag.Kurslar" class="form-control"></select>
    </div>

    <button type="submit" class="btn btn-secondary">Kaydet</button>
    
</form>

Views/KursKayit/Index.cshtml
@model List<KursKayıt>
      <a href="/KursKayit/Create" class="btn btn-primary" >  Kayıt Ekle  </a>
<h2>KursKayit Listesi</h2>

<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 150px;">@Html.DisplayName("KayıtID")</th>
            <th>@Html.DisplayName("OgrenciAd")</th>
            <th>@Html.DisplayName("Kurs")</th>
            <th style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

         <tr>

            <td>@item.KayıtId.ToString()</td>
             <td>@item.Ogrenci.AdSoyad</td>
            <td>@item.Kurs.Baslik</td>
            <td>
                                  
                   
                   <form asp-controller="KursKayit" asp-action="Delete" method="post">
                      <a asp-controller="KursKayit"  asp-action="Edit"   class="btn btn-sm btn-primary">Detay and Edit</a>
                    <input  type="hidden" value="@item.Kurs.KursId" name="id">
                    <button type="submit" asp-controller="KursKayit" asp-action="Delete"  class="btn btn-sm btn-danger">Delete</button>

                   </form> 
            </td>
            </tr>



        }
    

    </tbody>
</table> 



<td>
</td>
</tr>

Views/Ogrenci/Create.cshtml
@model Ogrenci


<form asp-controller="Ogrenci" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="OgrenciAd" class="form-label">Öğrenci Adı</label>
        <input asp-for="OgrenciAd" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="OgrenciSoyad" class="form-label">Öğrenci Soyad</label>
        <input asp-for="OgrenciSoyad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Eposta" class="form-label">Eposta</label>
        <input asp-for="Eposta" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Telefon" class="form-label">Telefon</label>
        <input asp-for="Telefon" class="form-control">
    </div>
    <button type="submit" class="btn btn-secondary">Kaydet</button>

    
</form>

Views/Ogrenci/Delete.cshtml
@model Ogrenci


<p>
    <b>@Model.OgrenciAd @Model.OgrenciSoyad</b> İSİMLİ ÖĞRENCİYİ SİLMEK İSTİYOR MUSUNUZ 


        <form asp-action="ToDelete" method="post" >
         <input  type="hidden" value="@Model.Id" name="id">

            <button  type="submit"  class="btn btn-danger" >  Evet  </button>
            <a href="/Ogrenci" class="btn btn-primary">Hayır </a>


        </form>


</p>

Views/Ogrenci/Edit.cshtml
@model Ogrenci

<h2>Öğrenci Güncelle</h2>

<hr>


<div class="row">

    <div class="col-8">
        <form asp-controller="Ogrenci" asp-action="Edit" method="post">

            <input type="hidden" asp-for="Id">
            <div class="mb-3">
                <label asp-for="OgrenciAd" class="form-label">Öğrenci Adı</label>
                <input asp-for="OgrenciAd" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="OgrenciSoyad" class="form-label">Öğrenci Soyad</label>
                <input asp-for="OgrenciSoyad" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Eposta" class="form-label">Eposta</label>
                <input asp-for="Eposta" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Telefon" class="form-label">Telefon</label>
                <input asp-for="Telefon" class="form-control">
            </div>
            <button type="submit" class="btn btn-secondary">Kaydet</button>


        </form>

    </div>
    
    <div class="col-4">

        <h4>Kurslar</h4>
        <hr>

        <ul>
            @foreach(var item in @Model.KursKayitları){
                <li>@item.Kurs.Baslik</li>
            }
        </ul>


    </div>

</div>

Views/Ogrenci/Index.cshtml
@model IEnumerable<Ogrenci>
<table class="table">

    <a href="/Ogrenci/Create" class="btn btn-primary" >  Öğrenci Ekle  </a>

    <thead>

        <tr>
            <th>Öğrenci Id</th>
            <th>Öğrenci Ad</th>
            <th>Öğrenci Soyad</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var ogrenci in Model)
        {
            <tr>
                <td>@ogrenci.Id</td>
                <td>@ogrenci.OgrenciAd</td>
                <td>@ogrenci.OgrenciSoyad</td>
                <td>
                    <a asp-controller="Ogrenci"  asp-action="Edit" asp-route-id = "@ogrenci.Id"  class="btn btn-sm btn-primary">Detay and Edit</a>
                    <a asp-controller="Ogrenci" asp-action="Delete" asp-route-id = "@ogrenci.Id" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Ogretmen/Create.cshtml
@model Ogretmen


<form asp-controller="Ogretmen" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Ad" class="form-label">Öğretmen Adı</label>
        <input asp-for="Ad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Soyad" class="form-label">Öğretmen Soyad</label>
        <input asp-for="Soyad" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Eposta" class="form-label">Eposta</label>
        <input asp-for="Eposta" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Telefon" class="form-label">Telefon</label>
        <input asp-for="Telefon" class="form-control">
    </div>
        <div class="mb-3">
        <label asp-for="BaslamaTarihi" class="form-label">Başlama Tarihi</label>
        <input asp-for="BaslamaTarihi" class="form-control">
    </div>
    <button type="submit" class="btn btn-secondary">Kaydet</button>

    
</form>

Views/Ogretmen/Delete.cshtml
@model Ogretmen


<p>
    <b>@Model.Ad @Model.Soyad</b> İSİMLİ ÖĞRETMENİ SİLMEK İSTİYOR MUSUNUZ 


        <form asp-action="ToDelete" method="post" >
         <input  type="hidden" value="@Model.OgretmenId" name="id">

            <button  type="submit"  class="btn btn-danger" >  Evet  </button>
            <a href="/Ogretmen" class="btn btn-primary">Hayır </a>


        </form>


</p>

Views/Ogretmen/Edit.cshtml
@model Ogretmen

<h2>Öğrenci Güncelle</h2>

<hr>


<div class="row">

    <div class="col-8">
        <form asp-controller="Ogretmen" asp-action="Edit" method="post">

            <input type="hidden" asp-for="OgretmenId">
            <div class="mb-3">
                <label asp-for="Ad" class="form-label">Öğretmen Adı</label>
                <input asp-for="Ad" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Soyad" class="form-label">Öğretmen Soyad</label>
                <input asp-for="Soyad" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Eposta" class="form-label">Eposta</label>
                <input asp-for="Eposta" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Telefon" class="form-label">Telefon</label>
                <input asp-for="Telefon" class="form-control">
            </div>
                  <div class="mb-3">
                <label asp-for="BaslamaTarihi" class="form-label">Başlama Tarihi</label>
                <input asp-for="BaslamaTarihi" class="form-control">
            </div>
            <button type="submit" class="btn btn-secondary">Kaydet</button>


        </form>

    </div>
    
    @* <div class="col-4">

        <h4>Kurslar</h4>
        <hr>

        <ul>
            @foreach(var item in @Model.KursKayitları){
                <li>@item.Kurs.Baslik</li>
            }
        </ul>


    </div> *@

</div>

Views/Ogretmen/Index.cshtml
@model IEnumerable<Ogretmen>
<table class="table">

    <a href="/Ogretmen/Create" class="btn btn-primary" >  Öğretmen Ekle  </a>

    <thead>

        <tr>
            <th>Öğretmen Id</th>
            <th>Öğretmen Ad</th>
            <th>Öğretmen Soyad</th>
            <th> Başlama Tarihi</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var ogretmen in Model)
        {
            <tr>
                <td>@ogretmen.OgretmenId</td>
                <td>@ogretmen.Ad</td>
                <td>@ogretmen.Soyad</td>
                <td>@(ogretmen.BaslamaTarihi.ToShortDateString())</td>
                <td>
                    <a asp-controller="Ogretmen"  asp-action="Edit" asp-route-id = "@ogretmen.OgretmenId"  class="btn btn-sm btn-primary">Detay and Edit</a>
                    <a asp-controller="Ogretmen" asp-action="Delete" asp-route-id = "@ogretmen.OgretmenId" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EntityApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EntityApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EntityApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ogrenci" asp-action="">Ogrenciler</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kurs" asp-action="">Kurslar</a>
                        </li>
                                                  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ogretmen" asp-action="">Öğretmenler</a>
                        </li>
                              <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="KursKayit" asp-action="">Kurslar Kayıtları</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EntityApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>